
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  app:
    build: .
    ports:
      - "8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://nrgpostge:5432/nrgpostge_db
      - DATASOURCE_USERNAME=nrg_user
      - DATASOURCE_PASSWORD=123
      - DATA_REDIS_HOST=nrgcache
      - DATA_REDIS_PORT=6379
      - APP_UPLOAD_DIR=/storage
    volumes:
      - ./provisional-storage:/storage
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - nrgpostge
      - nrgcache

  nrgpostge:
    image: postgres:16
    environment:
      - POSTGRES_DB=nrgpostge_db
      - POSTGRES_USER=nrg_user
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nrgcache:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres-data: